[theme]
 
# Primary accent for interactive elements
primaryColor = '#00796B'  # Verde bosque, transmite frescura y sostenibilidad
 
# Background color for the main content area
backgroundColor = '#E8F5E9'  # Verde claro suave para mayor claridad y conexión con la naturaleza
 
# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#A5D6A7'  # Verde suave para generar armonía y balance visual
 
# Color used for almost all text
textColor = '#1B5E20'  # Verde oscuro, fácil de leer y natural
 
# Font family for all text in the app, except code blocks
font = "sans-serif"  # Sans-serif para un aspecto profesional y moderno, adecuado para temas ambientales
